[package]
name = "hydrate-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hydrate-base = { path = "../hydrate-base" }
hydrate-model = { path = "../hydrate-model" }

log = "0.4.14"
crossbeam-channel = "0.5"