[package]
name = "hydrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hydrate-editor = { path = "../hydrate-editor" }
hydrate-model = { path = "../hydrate-model" }
hydrate-loader = { path = "../hydrate-loader" }