[package]
name = "refdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.4"
uuid = "0.8.2"
log = "0.4.14"
slotmap = "1.0.5"


